### ISSUE TITLE
Control Work # 0

### ISSUE THREAD

**Issue by oleksandrblazhko** [OS-IS/ai201-evchev#4]
Правильна відповідь на контрольне запитання дозволить вам отримати додаткові 2 бали 
до балів за виконання лабораторної роботи, якщо ви виявите бажання надати таку відповідь.
Відповідайте на запитання через коментар.

Запитання
11) Відомо, що всі сучасні засоби аутентифікації використовують комбінацію 
щонайменше двох з трьох класів: «те, що знаю», «те, чим володію», «те, чим є». 
Вкажіть, будь ласка, які два класи використовуються 
для безпечної взаємодії з GitHub-сервером та обґрунтуйте свій вибір.

**Comment by EvchevDenis** [comment]
Два класи використовуються для безпечної взаємодії з GitHub-сервером - це «те, що знаю» та «те, чим володію». Перший засіб для використання паролю для облікового запису GitHub або персонального токену доступу. Другий засіб передбачає аутентифікацію за допомогою SSH-ключів, де приватний ключ зберігається на локальному комп'ютері користувача, а публічний — на сервері GitHub або двофакторна аутентифікація.
Використання «те, що знаю» забезпечує стандартний підхід до аутентифікації через паролі або токени, а використання "те, чим володію" значно підвищує безпеку, оскільки зловмиснику недостатньо знати лише пароль або токен для доступу.

**Comment by oleksandrblazhko** [comment]
Рішення прийнято.
Оцінка = 2 бали
Дякую.
